# Generated by Django 4.1.6 on 2023-02-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celsius", models.FloatField()),
                ("fahrenheit", models.FloatField()),
                ("humidity", models.FloatField()),
                ("pressure", models.FloatField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
